import { existsSync, readFileSync } from "node:fs";
import { callJsonAgent } from "./ai-transport.mjs";
import { getAgentDefinition } from "./agent-registry.mjs";
import { executeRuntimeAction } from "./object-runtime.mjs";
import { persistAgentTurn } from "./agent-runtime.mjs";
import { buildFallback, buildIntegrationPackage, buildOrchestratorAnswer } from "./panda-packets.mjs";
import { createSupabaseServerClient, runtimeMode } from "./supabase-client.mjs";

const systemPrompt = `You are Panda, a DeepSeek-backed campaign orchestration agent for Hilti Agentic E2E.
Return only compact JSON. Ground your output in this product truth:
- Agent is the brain. The campaign plan is generated by agents, gated by humans, then executed.
- Required gates are H1 Plan, H2 Content + QA, H3 Rollout & Publish Readiness, H4 Performance Insights & Optimization.
- R-1 scope is A0, A1, A2, CP1, CP2, CP3, CP4, C1, C2, C4, R10, R11 plus orchestrator.
- R-1/RMB coverage must expose missing HOL, email, social/HN, rollout, and optimization outputs honestly.
- C2 compliance and R11 paid-media QA are evidence, not standalone gates.
- No auto-publish. H3 is the spend/live authorization.
- For phase=planning, create A0/A1/A2 artifacts and an H1 gate packet.
- The planning response must include one artifact with type "campaign-plan.v3"; its data object must include heroProduct, markets, locales, audience, budget, timeline, channels, kpis, and assumptions. Each channel must include id, name, owner, objective, requiredAssets, and rolloutTarget.
- For phase=content, create CP1/CP2/CP3/CP4/C1/C2/C4 artifacts and an H2 gate packet.
- For phase=rollout, create rollout tool-lane evidence for Figma/localization, Sprinklr, Contentful, SFMC/email, paid platforms, R10, R11, and H3 held publish.
- For phase=optimize, create performance insights and optimization recommendations for paid media, HOL landing pages, and HOL banners before knowledge promotion.
- Every artifact must include tool, owner, integrationMode, authority, gate, and evidence.
JSON shape:
{"summary": string, "worklog": [{"agent": string, "status": "done"|"running"|"blocked"|"queued", "message": string}], "artifacts": [{"name": string, "type": string, "content": string, "data": object, "tool": string, "owner": string, "integrationMode": string, "authority": string, "gate": string, "evidence": string}], "gate": {"id": "H1"|"H2"|"H3"|"H4"|"H-C"|"H-legal", "recommendation": string, "risk": "low"|"medium"|"high"}, "next_actions": string[]}`;

const orchestratorPrompt = `You are Panda, the global campaign orchestrator for Hilti Agentic E2E.
Answer the user's campaign question from the provided run context.
Rules:
- Be concise, operational, and grounded in the campaign data.
- Explain blockers, missing approvals, owner responsibilities, handoffs, and next actions.
- Never claim live publish/spend happened. H3 is required for live authorization.
- Route work to the right workspace: Campaign Planning, Content Planning, Content, Rollout, Optimize, Progress, or Skills.
- Return only compact JSON with this shape:
{"answer": string, "highlights": string[], "suggested_actions": string[], "route": string}`;

export async function handlePandaApiRequest(req, res) {
  setCors(res);
  if (req.method === "OPTIONS") return sendJson(res, 204, null);

  const pathname = getPathname(req);
  if (pathname === "/api/health") return handleHealth(req, res);
  if (pathname === "/api/agent") return handleAgent(req, res);
  if (pathname === "/api/orchestrator") return handleOrchestrator(req, res);
  if (pathname === "/api/integrations/status") return handleIntegrationStatus(req, res);
  if (pathname === "/api/integrations/package") return handleIntegrationPackage(req, res);

  return sendJson(res, 404, { error: "Not found" });
}

export async function handleHealth(_req, res) {
  setCors(res);
  return sendJson(res, 200, { ok: true, deepseek: Boolean(process.env.DEEPSEEK_API_KEY) });
}

export async function handleAgent(req, res) {
  setCors(res);
  if (req.method === "OPTIONS") return sendJson(res, 204, null);
  if (req.method !== "POST") return sendJson(res, 405, { error: "Method not allowed" });

  const payload = await readJson(req);
  const fallback = buildFallback(payload);
  const campaignId = resolveCampaignId(payload);
  const workspace = workspaceForPhase(payload.phase);
  const supabase = createSupabaseServerClient();

  let result;
  try {
    result = await callJsonAgent({
      payload,
      systemPrompt,
      fallback,
      normalize: (data, _payload, mode) => normalizeResponse(data, payload, mode),
    });
  } catch (error) {
    result = { mode: "fixture", warning: error instanceof Error ? error.message : "Agent call failed", ...fallback };
  }

  const persistence = await persistTurnIfConfigured({
    supabase,
    campaignId,
    workspace,
    agentId: "home-orchestrator",
    userText: resolveAgentInstruction(payload),
    answerText: responseSummary(result, fallback),
    result,
  });
  if (!persistence.ok) return sendJson(res, persistence.status, persistence.body);

  return sendJson(res, 200, result);
}

export async function handleOrchestrator(req, res) {
  setCors(res);
  if (req.method === "OPTIONS") return sendJson(res, 204, null);
  if (req.method !== "POST") return sendJson(res, 405, { error: "Method not allowed" });

  const payload = await readJson(req);
  const agent = getAgentDefinition(payload.agent_scope);
  const fallback = buildOrchestratorAnswer(payload);
  const campaignId = resolveCampaignId(payload);
  const workspace = resolveWorkspaceFromScope(payload.agent_scope, payload.current_view);
  const mode = runtimeMode();
  const supabase = mode === "supabase" ? createSupabaseServerClient() : undefined;

  let result;
  try {
    result = await callJsonAgent({
      payload,
      systemPrompt: agent.systemPrompt,
      fallback,
      normalize: (data, _payload, mode) => normalizeOrchestratorResponse(data, payload, mode),
    });
  } catch (error) {
    result = { mode: "fixture", warning: error instanceof Error ? error.message : "Orchestrator call failed", ...fallback };
  }

  const persistence = await persistTurnIfConfigured({
    supabase,
    campaignId,
    workspace,
    agentId: agent.id,
    userText: resolveOrchestratorQuestion(payload),
    answerText: responseAnswer(result, fallback),
    result,
  });
  if (!persistence.ok) return sendJson(res, persistence.status, persistence.body);

  const updateExecution = await executeOrchestratorUpdates({
    mode,
    supabase,
    result,
    campaignId,
    workspace,
    actor: agent.id,
  });
  if (!updateExecution.ok) return sendJson(res, updateExecution.status, updateExecution.body);
  result = updateExecution.result;

  return sendJson(res, 200, result);
}

export async function handleIntegrationStatus(_req, res) {
  setCors(res);
  return sendJson(res, 200, integrationStatus());
}

export async function handleIntegrationPackage(req, res) {
  setCors(res);
  if (req.method === "OPTIONS") return sendJson(res, 204, null);
  if (req.method !== "POST") return sendJson(res, 405, { error: "Method not allowed" });

  const payload = await readJson(req);
  return sendJson(res, 200, buildIntegrationPackage(payload));
}

export function loadEnv(path) {
  if (!existsSync(path)) return;
  const lines = readFileSync(path, "utf8").split(/\r?\n/);
  for (const line of lines) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2];
  }
}

function normalizeResponse(data, payload, mode) {
  const fallback = buildFallback(payload);
  const merged = {
    ...fallback,
    ...(data && typeof data === "object" ? data : {}),
  };

  const gateIds = new Set(["H1", "H2", "H3", "H4", "H-C", "H-legal"]);
  const risks = new Set(["low", "medium", "high"]);
  const statuses = new Set(["done", "running", "blocked", "queued"]);
  const normalizedGate = {
    id: gateIds.has(merged.gate?.id) ? merged.gate.id : fallback.gate.id,
    recommendation: typeof merged.gate?.recommendation === "string" ? merged.gate.recommendation : fallback.gate.recommendation,
    risk: risks.has(merged.gate?.risk) ? merged.gate.risk : fallback.gate.risk,
  };

  return {
    mode,
    warning: typeof merged.warning === "string" ? merged.warning : undefined,
    summary: typeof merged.summary === "string" ? merged.summary : fallback.summary,
    worklog: Array.isArray(merged.worklog)
      ? merged.worklog.slice(0, 12).map((entry) => ({
          agent: typeof entry.agent === "string" ? entry.agent : "orchestrator",
          status: statuses.has(entry.status) ? entry.status : "done",
          message: typeof entry.message === "string" ? entry.message : "Completed.",
        }))
      : fallback.worklog,
    artifacts: Array.isArray(merged.artifacts)
      ? merged.artifacts.slice(0, 12).map((artifact, index) => {
          const fallbackArtifact = fallback.artifacts[index] && typeof fallback.artifacts[index] === "object" ? fallback.artifacts[index] : {};
          return {
            name: typeof artifact.name === "string" ? artifact.name : "Artifact",
            type: typeof artifact.type === "string" ? artifact.type : "unknown",
            content: typeof artifact.content === "string" ? artifact.content : JSON.stringify(artifact.data || artifact).slice(0, 900),
            data: artifact.data && typeof artifact.data === "object" ? artifact.data : {},
            tool: typeof artifact.tool === "string" ? artifact.tool : fallbackArtifact.tool,
            owner: typeof artifact.owner === "string" ? artifact.owner : fallbackArtifact.owner,
            integrationMode: typeof artifact.integrationMode === "string" ? artifact.integrationMode : fallbackArtifact.integrationMode,
            authority: typeof artifact.authority === "string" ? artifact.authority : fallbackArtifact.authority,
            gate: typeof artifact.gate === "string" ? artifact.gate : fallbackArtifact.gate,
            evidence: typeof artifact.evidence === "string" ? artifact.evidence : fallbackArtifact.evidence,
          };
        })
      : fallback.artifacts,
    gate: normalizedGate,
    next_actions: Array.isArray(merged.next_actions) ? merged.next_actions.filter((item) => typeof item === "string").slice(0, 6) : fallback.next_actions,
  };
}

const ALLOWED_UPDATE_ACTIONS = new Set([
  "update_campaign_plan",
  "update_planning_object",
  "update_content_requirements",
  "update_content_object",
  "update_rollout_lane",
]);

const ALLOWED_WORK_OBJECT_STATUSES = new Set([
  "draft",
  "in-review",
  "approved",
  "revision-requested",
  "blocked",
]);

function normalizeUpdates(updates) {
  if (!Array.isArray(updates)) return [];
  return updates
    .filter(
      (update) =>
        update &&
        typeof update === "object" &&
        typeof update.action === "string" &&
        ALLOWED_UPDATE_ACTIONS.has(update.action) &&
        typeof update.note === "string" &&
        update.note.trim().length > 0,
    )
    .slice(0, 8)
    .map((update) => ({
      action: update.action,
      note: update.note.trim().slice(0, 500),
      targetId: typeof update.targetId === "string" ? update.targetId.trim().slice(0, 128) : undefined,
      status: typeof update.status === "string" && ALLOWED_WORK_OBJECT_STATUSES.has(update.status) ? update.status : undefined,
      payload: update.payload && typeof update.payload === "object" && !Array.isArray(update.payload) ? update.payload : undefined,
    }));
}

export function normalizeOrchestratorResponse(data, payload, mode) {
  const fallback = buildOrchestratorAnswer(payload);
  const merged = {
    ...fallback,
    ...(data && typeof data === "object" ? data : {}),
  };

  const updates = normalizeUpdates(merged.updates);

  return {
    mode,
    warning: typeof merged.warning === "string" ? merged.warning : undefined,
    answer: typeof merged.answer === "string" ? merged.answer : fallback.answer,
    highlights: Array.isArray(merged.highlights) ? merged.highlights.filter((item) => typeof item === "string").slice(0, 6) : fallback.highlights,
    suggested_actions: Array.isArray(merged.suggested_actions)
      ? merged.suggested_actions.filter((item) => typeof item === "string").slice(0, 6)
      : fallback.suggested_actions,
    route: typeof merged.route === "string" ? merged.route : fallback.route,
    ...(updates.length > 0 ? { updates } : {}),
  };
}

function integrationStatus() {
  return {
    deepseek: process.env.DEEPSEEK_API_KEY ? "live" : "missing-key",
    figma: process.env.FIGMA_TOKEN ? "configured" : "stub",
    contentful: process.env.CONTENTFUL_CMA_TOKEN ? "configured" : "stub",
    meta_ads: "file-export",
    google_ads: "file-export",
    linkedin_ads: "file-export",
    h3_publish: "human-gated",
  };
}

function getPathname(req) {
  if (req.url?.startsWith("/")) return new URL(req.url, "http://localhost").pathname;
  if (req.url) return new URL(req.url).pathname;
  return "";
}

function setCors(res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Headers", "content-type");
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
}

function sendJson(res, status, value) {
  if (status === 204) {
    res.writeHead(status);
    res.end();
    return;
  }

  res.writeHead(status, { "Content-Type": "application/json" });
  res.end(JSON.stringify(value));
}

async function readJson(req) {
  if (req.body && typeof req.body === "object") return req.body;

  const body = await readBody(req);
  try {
    return JSON.parse(body || "{}");
  } catch {
    return {};
  }
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let body = "";
    req.on("data", (chunk) => {
      body += chunk;
    });
    req.on("end", () => resolve(body));
    req.on("error", reject);
  });
}

async function persistTurnIfConfigured({ supabase, campaignId, workspace, agentId, userText, answerText, result }) {
  if (!supabase) return { ok: true };

  try {
    await persistAgentTurn({
      campaignId,
      workspace,
      agentId,
      userText,
      answerText,
      modelMode: typeof result.mode === "string" ? result.mode : "unknown",
      supabase,
    });
    return { ok: true };
  } catch (error) {
    return {
      ok: false,
      status: 503,
      body: buildPersistenceFailureBody(result, error),
    };
  }
}

function resolveCampaignId(payload) {
  return typeof payload.campaign_id === "string" && payload.campaign_id.trim()
    ? payload.campaign_id.trim()
    : typeof payload.campaignId === "string" && payload.campaignId.trim()
    ? payload.campaignId.trim()
    : "unknown-campaign";
}

function workspaceForPhase(phase) {
  if (phase === "planning") return "campaign-planning";
  if (phase === "content") return "content";
  if (phase === "rollout") return "rollout";
  if (phase === "optimize") return "optimize";
  return "home";
}

function resolveWorkspaceFromScope(agentScope, currentView) {
  if (typeof agentScope?.surface === "string" && agentScope.surface.trim()) return agentScope.surface.trim();
  if (typeof agentScope?.view === "string" && agentScope.view.trim()) return agentScope.view.trim();
  if (typeof currentView === "string" && currentView.trim()) return currentView.trim();
  return "home";
}

function resolveAgentInstruction(payload) {
  if (typeof payload.instruction === "string" && payload.instruction.trim()) return payload.instruction.trim();
  if (typeof payload.question === "string" && payload.question.trim()) return payload.question.trim();
  if (typeof payload.brief === "string" && payload.brief.trim()) return payload.brief.trim();
  return "Create the next gate-ready artifact packet.";
}

function resolveOrchestratorQuestion(payload) {
  if (typeof payload.question === "string" && payload.question.trim()) return payload.question.trim();
  if (typeof payload.instruction === "string" && payload.instruction.trim()) return payload.instruction.trim();
  return "What should Panda do next?";
}

function responseSummary(result, fallback) {
  if (typeof result.summary === "string" && result.summary.trim()) return result.summary.trim();
  if (typeof result.answer === "string" && result.answer.trim()) return result.answer.trim();
  return typeof fallback.summary === "string" ? fallback.summary : "Panda packet is ready.";
}

function responseAnswer(result, fallback) {
  if (typeof result.answer === "string" && result.answer.trim()) return result.answer.trim();
  if (typeof result.summary === "string" && result.summary.trim()) return result.summary.trim();
  return typeof fallback.answer === "string" ? fallback.answer : "Panda is ready.";
}

function buildPersistenceFailureBody(result, error) {
  const details = error instanceof Error ? error.message : "Durable runtime persistence failed";
  return {
    error: "Durable runtime persistence failed",
    details,
    ...(typeof result.warning === "string" && result.warning.trim() ? { warning: result.warning } : {}),
  };
}

function buildUpdateFailureBody(result, error) {
  const details = error instanceof Error ? error.message : "Durable runtime update execution failed";
  return {
    error: "Durable runtime update execution failed",
    details,
    ...(typeof result.warning === "string" && result.warning.trim() ? { warning: result.warning } : {}),
  };
}

async function executeOrchestratorUpdates({ mode, supabase, result, campaignId, workspace, actor }) {
  if (mode !== "supabase" || !supabase || !Array.isArray(result.updates) || result.updates.length === 0) {
    return { ok: true, result };
  }

  try {
    const executions = [];
    for (const update of result.updates) {
      const execution = await executeRuntimeAction({
        action: update,
        campaignId,
        workspace,
        actor,
        supabase,
      });
      executions.push(execution);
    }

    const events = executions.flatMap((execution) => (Array.isArray(execution.events) ? execution.events : []));
    const snapshots = executions.map((execution) => execution.snapshot).filter((snapshot) => snapshot !== undefined);

    return {
      ok: true,
      result: {
        ...result,
        ...(events.length > 0 ? { events } : {}),
        ...(snapshots.length > 0 ? { snapshot: snapshots[snapshots.length - 1] } : {}),
      },
    };
  } catch (error) {
    return {
      ok: false,
      status: 503,
      body: buildUpdateFailureBody(result, error),
    };
  }
}
