/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EvalRouteImport } from './routes/eval'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as ContentCampaignIdRouteImport } from './routes/content.$campaignId'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'
import { Route as ApiArchetypeSelectRouteImport } from './routes/api/archetype-select'
import { Route as ApiAdaptPlanRouteImport } from './routes/api/adapt-plan'
import { Route as ApiExecuteNodeRouteImport } from './routes/api/execute-node'
import { Route as ApiConnectorRolloutRouteImport } from './routes/api/connector-rollout'

const SkillsRoute = SkillsRouteImport.update({ id: '/skills', path: '/skills', getParentRoute: () => rootRouteImport } as any)
const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const EvalRoute = EvalRouteImport.update({ id: '/eval', path: '/eval', getParentRoute: () => rootRouteImport } as any)
const CampaignsRoute = CampaignsRouteImport.update({ id: '/campaigns', path: '/campaigns', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ContentIndexRoute = ContentIndexRouteImport.update({ id: '/content/', path: '/content/', getParentRoute: () => rootRouteImport } as any)
const ContentCampaignIdRoute = ContentCampaignIdRouteImport.update({ id: '/content/$campaignId', path: '/content/$campaignId', getParentRoute: () => rootRouteImport } as any)
const CampaignIdRoute = CampaignIdRouteImport.update({ id: '/campaign/$id', path: '/campaign/$id', getParentRoute: () => rootRouteImport } as any)
const ApiArchetypeSelectRoute = ApiArchetypeSelectRouteImport.update({ id: '/api/archetype-select', path: '/api/archetype-select', getParentRoute: () => rootRouteImport } as any)
const ApiAdaptPlanRoute = ApiAdaptPlanRouteImport.update({ id: '/api/adapt-plan', path: '/api/adapt-plan', getParentRoute: () => rootRouteImport } as any)
const ApiExecuteNodeRoute = ApiExecuteNodeRouteImport.update({ id: '/api/execute-node', path: '/api/execute-node', getParentRoute: () => rootRouteImport } as any)
const ApiConnectorRolloutRoute = ApiConnectorRolloutRouteImport.update({ id: '/api/connector-rollout', path: '/api/connector-rollout', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute; '/campaigns': typeof CampaignsRoute; '/eval': typeof EvalRoute
  '/settings': typeof SettingsRoute; '/skills': typeof SkillsRoute
  '/api/adapt-plan': typeof ApiAdaptPlanRoute; '/api/archetype-select': typeof ApiArchetypeSelectRoute
  '/api/execute-node': typeof ApiExecuteNodeRoute; '/api/connector-rollout': typeof ApiConnectorRolloutRoute
  '/campaign/$id': typeof CampaignIdRoute; '/content/$campaignId': typeof ContentCampaignIdRoute
  '/content/': typeof ContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute; '/campaigns': typeof CampaignsRoute; '/eval': typeof EvalRoute
  '/settings': typeof SettingsRoute; '/skills': typeof SkillsRoute
  '/api/adapt-plan': typeof ApiAdaptPlanRoute; '/api/archetype-select': typeof ApiArchetypeSelectRoute
  '/api/execute-node': typeof ApiExecuteNodeRoute; '/api/connector-rollout': typeof ApiConnectorRolloutRoute
  '/campaign/$id': typeof CampaignIdRoute; '/content/$campaignId': typeof ContentCampaignIdRoute
  '/content': typeof ContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport; '/': typeof IndexRoute; '/campaigns': typeof CampaignsRoute
  '/eval': typeof EvalRoute; '/settings': typeof SettingsRoute; '/skills': typeof SkillsRoute
  '/api/adapt-plan': typeof ApiAdaptPlanRoute; '/api/archetype-select': typeof ApiArchetypeSelectRoute
  '/api/execute-node': typeof ApiExecuteNodeRoute; '/api/connector-rollout': typeof ApiConnectorRolloutRoute
  '/campaign/$id': typeof CampaignIdRoute; '/content/$campaignId': typeof ContentCampaignIdRoute
  '/content/': typeof ContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campaigns' | '/eval' | '/settings' | '/skills' | '/api/adapt-plan' | '/api/archetype-select' | '/api/execute-node' | '/api/connector-rollout' | '/campaign/$id' | '/content/$campaignId' | '/content/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campaigns' | '/eval' | '/settings' | '/skills' | '/api/adapt-plan' | '/api/archetype-select' | '/api/execute-node' | '/api/connector-rollout' | '/campaign/$id' | '/content/$campaignId' | '/content'
  id: '__root__' | '/' | '/campaigns' | '/eval' | '/settings' | '/skills' | '/api/adapt-plan' | '/api/archetype-select' | '/api/execute-node' | '/api/connector-rollout' | '/campaign/$id' | '/content/$campaignId' | '/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute; CampaignsRoute: typeof CampaignsRoute; EvalRoute: typeof EvalRoute
  SettingsRoute: typeof SettingsRoute; SkillsRoute: typeof SkillsRoute
  ApiAdaptPlanRoute: typeof ApiAdaptPlanRoute; ApiArchetypeSelectRoute: typeof ApiArchetypeSelectRoute
  ApiExecuteNodeRoute: typeof ApiExecuteNodeRoute; ApiConnectorRolloutRoute: typeof ApiConnectorRolloutRoute
  CampaignIdRoute: typeof CampaignIdRoute; ContentCampaignIdRoute: typeof ContentCampaignIdRoute
  ContentIndexRoute: typeof ContentIndexRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': { id: '/skills'; path: '/skills'; fullPath: '/skills'; preLoaderRoute: typeof SkillsRouteImport; parentRoute: typeof rootRouteImport }
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
    '/eval': { id: '/eval'; path: '/eval'; fullPath: '/eval'; preLoaderRoute: typeof EvalRouteImport; parentRoute: typeof rootRouteImport }
    '/campaigns': { id: '/campaigns'; path: '/campaigns'; fullPath: '/campaigns'; preLoaderRoute: typeof CampaignsRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/content/': { id: '/content/'; path: '/content'; fullPath: '/content/'; preLoaderRoute: typeof ContentIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/content/$campaignId': { id: '/content/$campaignId'; path: '/content/$campaignId'; fullPath: '/content/$campaignId'; preLoaderRoute: typeof ContentCampaignIdRouteImport; parentRoute: typeof rootRouteImport }
    '/campaign/$id': { id: '/campaign/$id'; path: '/campaign/$id'; fullPath: '/campaign/$id'; preLoaderRoute: typeof CampaignIdRouteImport; parentRoute: typeof rootRouteImport }
    '/api/archetype-select': { id: '/api/archetype-select'; path: '/api/archetype-select'; fullPath: '/api/archetype-select'; preLoaderRoute: typeof ApiArchetypeSelectRouteImport; parentRoute: typeof rootRouteImport }
    '/api/adapt-plan': { id: '/api/adapt-plan'; path: '/api/adapt-plan'; fullPath: '/api/adapt-plan'; preLoaderRoute: typeof ApiAdaptPlanRouteImport; parentRoute: typeof rootRouteImport }
    '/api/execute-node': { id: '/api/execute-node'; path: '/api/execute-node'; fullPath: '/api/execute-node'; preLoaderRoute: typeof ApiExecuteNodeRouteImport; parentRoute: typeof rootRouteImport }
    '/api/connector-rollout': { id: '/api/connector-rollout'; path: '/api/connector-rollout'; fullPath: '/api/connector-rollout'; preLoaderRoute: typeof ApiConnectorRolloutRouteImport; parentRoute: typeof rootRouteImport }
  }
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute, CampaignsRoute, EvalRoute, SettingsRoute, SkillsRoute,
  ApiAdaptPlanRoute, ApiArchetypeSelectRoute, ApiExecuteNodeRoute, ApiConnectorRolloutRoute,
  CampaignIdRoute, ContentCampaignIdRoute, ContentIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> }
}
