/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EvalRouteImport } from './routes/eval'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as ContentCampaignIdRouteImport } from './routes/content.$campaignId'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRoute = EvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCampaignIdRoute = ContentCampaignIdRouteImport.update({
  id: '/content/$campaignId',
  path: '/content/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRoute = CampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/eval': typeof EvalRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/content/$campaignId': typeof ContentCampaignIdRoute
  '/content/': typeof ContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/eval': typeof EvalRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/content/$campaignId': typeof ContentCampaignIdRoute
  '/content': typeof ContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/eval': typeof EvalRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/content/$campaignId': typeof ContentCampaignIdRoute
  '/content/': typeof ContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/eval'
    | '/settings'
    | '/skills'
    | '/campaign/$id'
    | '/content/$campaignId'
    | '/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/eval'
    | '/settings'
    | '/skills'
    | '/campaign/$id'
    | '/content/$campaignId'
    | '/content'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/eval'
    | '/settings'
    | '/skills'
    | '/campaign/$id'
    | '/content/$campaignId'
    | '/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  EvalRoute: typeof EvalRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  CampaignIdRoute: typeof CampaignIdRoute
  ContentCampaignIdRoute: typeof ContentCampaignIdRoute
  ContentIndexRoute: typeof ContentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval': {
      id: '/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof EvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$campaignId': {
      id: '/content/$campaignId'
      path: '/content/$campaignId'
      fullPath: '/content/$campaignId'
      preLoaderRoute: typeof ContentCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id': {
      id: '/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof CampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  EvalRoute: EvalRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  CampaignIdRoute: CampaignIdRoute,
  ContentCampaignIdRoute: ContentCampaignIdRoute,
  ContentIndexRoute: ContentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
